openapi: "3.0.2"
info:
  title: Signer API
  version: "0.1.0"
  description: API that allows commit modules to request generic signatures from validators
tags:
  - name: Signer
  - name: Management
paths:
  /signer/v1/get_pubkeys:
    get:
      operationId: getPubkeys
      summary: Get a list of public keys for which signatures may be requested
      tags:
        - Signer
      security:
        - BearerAuth: []
      responses:
        "200":
          description: "All public keys available to the module: consensus pubkeys (BLS) and proxies (BLS pubkeys and ECDSA addresses)"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPubkeysResponse"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/InternalError"

  /signer/v1/request_signature:
    post:
      operationId: requestSignature
      summary: Send a signature request
      tags:
        - Signer
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestSignatureRequest"
            examples:
              Consensus:
                value:
                  type: "consensus"
                  pubkey: "0xa3ffa9241f78279f1af04644cb8c79c2d8f02bcf0e28e2f186f6dcccac0a869c2be441fda50f0dea895cfce2e53f0989"
                  object_root: "0x3e9f4a78b5c21d64f0b8e3d9a7f5c02b4d1e67a3c8f29b5d6e4a3b1c8f72e6d9"
              ProxyBls:
                value:
                  type: "proxy_bls"
                  proxy: "0xa3ffa9241f78279f1af04644cb8c79c2d8f02bcf0e28e2f186f6dcccac0a869c2be441fda50f0dea895cfce2e53f0989"
                  object_root: "0x3e9f4a78b5c21d64f0b8e3d9a7f5c02b4d1e67a3c8f29b5d6e4a3b1c8f72e6d9"
              ProxyEcdsa:
                value:
                  type: "proxy_ecdsa"
                  proxy: "0x71f65e9f6336770e22d148bd5e89b391a1c3b0bb"
                  object_root: "0x3e9f4a78b5c21d64f0b8e3d9a7f5c02b4d1e67a3c8f29b5d6e4a3b1c8f72e6d9"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignatureResult"
              examples:
                Consensus:
                  value: "0xa3ffa9241f78279f1af04644cb8c79c2d8f02bcf0e28e2f186f6dcccac0a869c2be441fda50f0dea895cfce2e53f0989a3ffa9241f78279f1af04644cb8c79c2d8f02bcf0e28e2f186f6dcccac0a869c2be441fda50f0dea895cfce2e53f0989"
                ProxyBls:
                  value: "0xa3ffa9241f78279f1af04644cb8c79c2d8f02bcf0e28e2f186f6dcccac0a869c2be441fda50f0dea895cfce2e53f0989a3ffa9241f78279f1af04644cb8c79c2d8f02bcf0e28e2f186f6dcccac0a869c2be441fda50f0dea895cfce2e53f0989"
                ProxyEcdsa:
                  value: "0x985b495f49d1b96db3bba3f6c5dd1810950317c10d4c2042bd316f338cdbe74359072e209b85e56ac492092d7860063dd096ca31b4e164ef27e3f8d508e656801c"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "500":
          $ref: "#/components/responses/InternalError"

  /signer/v1/generate_proxy_key:
    post:
      operationId: generateProxyKey
      summary: Request a proxy key be generated for a specific consensus pubkey
      tags:
        - Signer
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GenerateProxyKeyRequest"
            examples:
              Bls:
                value:
                  pubkey: "0xa9e9cff900de07e295a044789fd4bdb6785eb0651ad282f9e76d12afd87e75180bdd64caf2e315b815d7322bd31ab48a"
                  scheme: "bls"
              Ecdsa:
                value:
                  pubkey: "0xa9e9cff900de07e295a044789fd4bdb6785eb0651ad282f9e76d12afd87e75180bdd64caf2e315b815d7322bd31ab48a"
                  scheme: "ecdsa"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenerateProxyKeyResponse"
              examples:
                Bls:
                  value:
                    message:
                      delegator: "0xa9e9cff900de07e295a044789fd4bdb6785eb0651ad282f9e76d12afd87e75180bdd64caf2e315b815d7322bd31ab48a"
                      proxy: "0xb646318d81b7cff3f8aae5040eab11927b4a99542c02970a1ab8069a83e5b76b302705d0b5e0054831ce2af72088bf30"
                    signature: "0x88274f2d78d30ae429cc16f5c64657b491ccf26291c821cf953da34f16d60947d4f245decdce4a492e8d8f949482051b184aaa890d5dd97788387689335a1fee37cbe55c0227f81b073ce6e93b45f96169f497ed322d3d384d79ccaa7846d5ab"
                Ecdsa:
                  value:
                    message:
                      delegator: "0xa9e9cff900de07e295a044789fd4bdb6785eb0651ad282f9e76d12afd87e75180bdd64caf2e315b815d7322bd31ab48a"
                      proxy: "0x71f65e9f6336770e22d148bd5e89b391a1c3b0bb"
                    signature: "0xb5b5b71d1701cc45086af3d3d86bf9d3c509442835e5b9f7734923edc9a6c538e743d70613cdef90b7e5b171fbbe6a29075b3f155e4bd66d81ff9dbc3b6d7fa677d169b2ceab727ffa079a31fe1fc0e478752e9da9566a9408e4db24ac6104db"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "500":
          $ref: "#/components/responses/InternalError"

  /status:
    get:
      operationId: getStatus
      summary: Get the status of the Signer API module
      tags:
        - Management
      responses:
        "200":
          description: Success
          content:
            text/plain:
              schema:
                type: string
                example: "OK"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Unauthorized request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            code: 401
            message: "Unauthorized"
    NotFoundError:
      description: Unknown value (pubkey, proxy, etc.)
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            code: 404
            message: "Unknown pubkey"
    InternalError:
      description: Internal error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            code: 500
            message: "Internal error"
  schemas:
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          example: 500
        message:
          type: string
          example: "Internal error"

    BlsPubkey:
      type: string
      format: hex
      pattern: "^0x[a-fA-F0-9]{96}$"
      example: "0xa9e9cff900de07e295a044789fd4bdb6785eb0651ad282f9e76d12afd87e75180bdd64caf2e315b815d7322bd31ab48a"

    EcdsaAddress:
      type: string
      format: hex
      pattern: "^0x[a-fA-F0-9]{40}$"
      example: "0x71f65e9f6336770e22d148bd5e89b391a1c3b0bb"

    BlsSignature:
      type: string
      format: hex
      pattern: "^0x[a-fA-F0-9]{192}$"
      example: "0xa3ffa9241f78279f1af04644cb8c79c2d8f02bcf0e28e2f186f6dcccac0a869c2be441fda50f0dea895cfce2e53f0989a3ffa9241f78279f1af04644cb8c79c2d8f02bcf0e28e2f186f6dcccac0a869c2be441fda50f0dea895cfce2e53f0989"

    EcdsaSignature:
      type: string
      format: hex
      pattern: "^0x[a-fA-F0-9]{130}$"
      example: "0x985b495f49d1b96db3bba3f6c5dd1810950317c10d4c2042bd316f338cdbe74359072e209b85e56ac492092d7860063dd096ca31b4e164ef27e3f8d508e656801c"

    ProxyIdentifier:
      oneOf:
        - $ref: "#/components/schemas/BlsPubkey"
        - $ref: "#/components/schemas/EcdsaAddress"

    SignatureResult:
      oneOf:
        - $ref: "#/components/schemas/BlsSignature"
        - $ref: "#/components/schemas/EcdsaSignature"

    SignerKeyMapping:
      type: object
      required:
        - consensus
        - proxy_bls
        - proxy_ecdsa
      properties:
        consensus:
          description: Consensus validator pubkey
          allOf:
            - $ref: "#/components/schemas/BlsPubkey"
        proxy_bls:
          description: BLS proxy pubkeys
          type: array
          items:
            $ref: "#/components/schemas/BlsPubkey"
        proxy_ecdsa:
          description: ECDSA proxy addresses
          type: array
          items:
            $ref: "#/components/schemas/EcdsaAddress"

    GetPubkeysResponse:
      type: object
      required:
        - keys
      properties:
        keys:
          description: List of mappings between consensus pubkeys and their proxies
          type: array
          items:
            $ref: "#/components/schemas/SignerKeyMapping"

    RequestSignatureRequest:
      type: object
      required:
        - type
        - object_root
      oneOf:
        - required:
            - pubkey
        - required:
            - proxy
      properties:
        type:
          description: Type of the sign request
          type: string
          enum: [consensus, proxy_bls, proxy_ecdsa]
        pubkey:
          description: Public key of the validator for consensus signatures
          allOf:
            - $ref: "#/components/schemas/BlsPubkey"
        proxy:
          description: BLS proxy pubkey or ECDSA address for proxy signatures
          allOf:
            - $ref: "#/components/schemas/ProxyIdentifier"
        object_root:
          description: The root of the object to be signed
          type: string
          format: hex
          pattern: "^0x[a-fA-F0-9]{64}$"
          example: "0x3e9f4a78b5c21d64f0b8e3d9a7f5c02b4d1e67a3c8f29b5d6e4a3b1c8f72e6d9"

    GenerateProxyKeyRequest:
      type: object
      required:
        - pubkey
        - scheme
      properties:
        pubkey:
          description: Validator BLS public key for which to generate a proxy key
          allOf:
            - $ref: "#/components/schemas/BlsPubkey"
        scheme:
          description: Signature scheme to generate proxy keypair for
          type: string
          enum: [bls, ecdsa]

    ProxyDelegationMessage:
      type: object
      required:
        - delegator
        - proxy
      properties:
        delegator:
          description: Validator BLS pubkey for which the proxy key was generated
          allOf:
            - $ref: "#/components/schemas/BlsPubkey"
        proxy:
          description: Generated proxy identifier (BLS pubkey or ECDSA address)
          allOf:
            - $ref: "#/components/schemas/ProxyIdentifier"

    GenerateProxyKeyResponse:
      type: object
      required:
        - message
        - signature
      properties:
        message:
          $ref: "#/components/schemas/ProxyDelegationMessage"
        signature:
          description: Signature of the proxy delegation
          allOf:
            - $ref: "#/components/schemas/BlsSignature"
